name: Java CI

on:
  push:
    branches: [ '**' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build & tests
        run: mvn -B clean verify
        working-directory: inventario

      - name: Static analysis
        run: |
          mvn -B checkstyle:checkstyle pmd:check
        working-directory: inventario

      - name: Upload quality reports
        uses: actions/upload-artifact@v4
        with:
          name: quality-reports
          path: inventario/target/site
